To run this, press "*Runtime*" and press "*Run all*" on a **free** Tesla T4 Google Colab instance!
<div class="align-center">
<a href="https://unsloth.ai/"><img src="https://github.com/unslothai/unsloth/raw/main/images/unsloth%20new%20logo.png" width="115"></a>
<a href="https://discord.gg/unsloth"><img src="https://github.com/unslothai/unsloth/raw/main/images/Discord button.png" width="145"></a>
<a href="https://unsloth.ai/docs/"><img src="https://github.com/unslothai/unsloth/blob/main/images/documentation%20green%20button.png?raw=true" width="125"></a> Join Discord if you need help + ⭐ <i>Star us on <a href="https://github.com/unslothai/unsloth">Github</a> </i> ⭐
</div>

To install Unsloth on your local device, follow [our guide](https://unsloth.ai/docs/get-started/install). This notebook is licensed [LGPL-3.0](https://github.com/unslothai/notebooks?tab=LGPL-3.0-1-ov-file#readme).

You will learn how to do [data prep](#Data), how to [train](#Train), how to [run the model](#Inference), & how to save it

### News

Introducing **[Unsloth Desktop](https://unsloth.ai/docs/desktop)**, the first desktop app to run and train models. Free and open-source for macOS, Windows and Linux. [GitHub](https://github.com/unslothai/unsloth) • [Download](https://unsloth.ai/download)

<p>
<a href="https://unsloth.ai/docs/desktop"><img src="https://raw.githubusercontent.com/unslothai/notebooks/refs/heads/main/assets/unsloth-qwen3-8.png" width="350" alt="Introducing Unsloth Desktop"></a>
</p>

Train MoEs - DeepSeek, GLM, Qwen and gpt-oss 12x faster with 35% less VRAM. [Blog](https://unsloth.ai/docs/new/faster-moe)

Ultra Long-Context Reinforcement Learning is here with 7x more context windows! [Blog](https://unsloth.ai/docs/new/grpo-long-context)

New in Reinforcement Learning: [FP8 RL](https://unsloth.ai/docs/new/fp8-reinforcement-learning) • [Vision RL](https://unsloth.ai/docs/new/vision-reinforcement-learning-vlm-rl) • [Standby](https://unsloth.ai/docs/basics/memory-efficient-rl) • [gpt-oss RL](https://unsloth.ai/docs/new/gpt-oss-reinforcement-learning)

Visit our docs for all our [model uploads](https://unsloth.ai/docs/get-started/unsloth-model-catalog) and [notebooks](https://unsloth.ai/docs/get-started/unsloth-notebooks).

### Import from Drive

In [2]:
from google.colab import drive
drive.mount("/content/drive")

adapter_path = "/content/drive/MyDrive/AI learning/gpt-oss-fable-lora-v1"

Mounted at /content/drive

In [3]:
import torch
from unsloth import FastLanguageModel

model, tokenizer = FastLanguageModel.from_pretrained(
    model_name=adapter_path,
    max_seq_length=1024,
    dtype=torch.float32,
    load_in_4bit=True,
    full_finetuning=False,
)

🦥 Unsloth: Will patch your computer to enable 2x faster free finetuning.
🦥 Unsloth Zoo will now patch everything to make training faster!
==((====))==  Unsloth 2026.9.12: Fast Gpt_Oss patching. Transformers: 4.56.2.
   \\   /|    Tesla T4. Num GPUs = 1. Max memory: 14.563 GB. Platform: Linux.
O^O/ \_/ \    Torch: 2.11.0+cu128. CUDA: 7.5. CUDA Toolkit: 12.8. Triton: 3.6.0
\        /    Bfloat16 = FALSE. FA [Xformers = None. FA2 = False]
 "-____-"     Free license: http://github.com/unslothai/unsloth
Unsloth: Fast downloading is enabled - ignore downloading bars which are red colored!
Unsloth: Using float16 precision for gpt_oss won't work! Using float32.

Loading checkpoint shards:   0%|          | 0/4 [00:00<?, ?it/s]

Unsloth: Offloading embeddings to RAM to save 1.08 GB.

WARNING:unsloth_zoo.log:Unsloth: Added `<|call|>` (id 200012) to the generation stop tokens. Harmony ends a tool call with it, and without it generation runs past a finished tool call into plain-text harmony markup.

### Chat with AI

In [4]:
FastLanguageModel.for_inference(model)

messages = [
    {"role": "user", "content": "Write a small Python function that reads a JSON file safely."}
]

inputs = tokenizer.apply_chat_template(
    messages,
    tokenize=True,
    add_generation_prompt=True,
    return_tensors="pt",
    reasoning_effort="low",
).to("cuda")

output = model.generate(
    input_ids=inputs,
    max_new_tokens=300,
    temperature=1.0,
    top_p=1.0,
    do_sample=True,
)

print(tokenizer.decode(output[0][inputs.shape[-1]:], skip_special_tokens=True))

The attention mask is not set and cannot be inferred from input because pad token is same as eos token. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
/usr/local/lib/python3.13/dist-packages/unsloth/import_fixes.py:5429: UserWarning: 'has_cuda' is deprecated, please use 'torch.backends.cuda.is_built()'
  return original(name)
/usr/local/lib/python3.13/dist-packages/unsloth/import_fixes.py:5429: UserWarning: 'has_cudnn' is deprecated, please use 'torch.backends.cudnn.is_available()'
  return original(name)
/usr/local/lib/python3.13/dist-packages/unsloth/import_fixes.py:5429: UserWarning: 'has_mps' is deprecated, please use 'torch.backends.mps.is_built()'
  return original(name)
/usr/local/lib/python3.13/dist-packages/unsloth/import_fixes.py:5429: UserWarning: 'has_mkldnn' is deprecated, please use 'torch.backends.mkldnn.is_available()'
  return original(name)

analysisNeed to provide Python code.assistantfinalHere’s a short, self‑contained Python function that safely reads a JSON file, handling the most common issues you’ll encounter when working with file I/O and JSON parsing.

```python
import json
from pathlib import Path
from typing import Any, Dict, Optional


def read_json_file(file_path: str | Path, *, default: Optional[Dict[Any, Any]] = None) -> Dict[Any, Any]:
    """
    Safely read a JSON file and return the parsed data.

    Parameters
    ----------
    file_path : str | Path
        Path to the JSON file.
    default : Optional[Dict[Any, Any]] = None
        Value to return if the file is missing or unreadable.
        Default is an empty dict.

    Returns
    -------
    Dict[Any, Any]
        Parsed JSON object.
    """
    # Convert to a Path object for convenience
    path = Path(file_path)

    # Check that the file exists and is indeed a file
    if not path.is_file():
        # If the file does not exist, return the default value
        return default if default is not None else {}

    try:
        # Open the file with the correct encoding
        with path.open("r", encoding="utf-8") as fh:
            # Load the JSON
            data = json.load(fh)

        # Return the parsed data
        return data

### Training

In [5]:
import json
import requests
from datasets import Dataset

LANG = "python"
TARGET_ROWS = 240
MAX_LENGTH = 1024

assert "tokenizer" in globals(), "请先运行模型加载格"

url = (
    "https://huggingface.co/datasets/bigcode/commitpackft/"
    f"resolve/main/data/{LANG}/data.jsonl"
)

rows = []
seen = set()
allowed_licenses = {
    "mit", "apache-2.0", "bsd-2-clause", "bsd-3-clause",
    "isc", "unlicense", "cc0-1.0",
}

with requests.get(url, stream=True, timeout=120) as response:
    response.raise_for_status()

    for raw_line in response.iter_lines():
        if not raw_line:
            continue

        item = json.loads(raw_line.decode("utf-8"))

        if (item.get("license") or "").lower() not in allowed_licenses:
            continue

        old_code = item.get("old_contents") or ""
        new_code = item.get("new_contents") or ""
        instruction = (item.get("subject") or "").strip()
        filename = item.get("old_file") or "file.py"

        if not old_code.strip() or not new_code.strip() or not instruction:
            continue
        if old_code == new_code:
            continue

        key = (old_code, new_code)
        if key in seen:
            continue

        user_prompt = (
            f"Modify this existing {LANG} file.\n\n"
            f"File: {filename}\n\n"
            f"Request:\n{instruction}\n\n"
            f"Current file:\n{old_code}\n\n"
            "Return the complete revised file only."
        )

        messages = [
            {"role": "user", "content": user_prompt},
            {"role": "assistant", "content": new_code},
        ]

        text = tokenizer.apply_chat_template(
            messages,
            tokenize=False,
            add_generation_prompt=False,
            reasoning_effort="low",
        )

        # 按完整聊天格式计算长度；超长样本跳过
        token_count = len(
            tokenizer(text, add_special_tokens=False)["input_ids"]
        )
        if token_count > MAX_LENGTH:
            continue

        seen.add(key)
        rows.append({"text": text})

        if len(rows) >= TARGET_ROWS:
            break

print("可用样本：", len(rows))
assert len(rows) >= 30, "短样本不足，暂时不要开始训练"

commit_data = Dataset.from_list(rows).train_test_split(
    test_size=0.1,
    seed=42,
)

print(commit_data)
print(commit_data["train"][0]["text"][:800])

可用样本： 240
DatasetDict({
    train: Dataset({
        features: ['text'],
        num_rows: 216
    })
    test: Dataset({
        features: ['text'],
        num_rows: 24
    })
})
<|start|>system<|message|>You are ChatGPT, a large language model trained by OpenAI.
Knowledge cutoff: 2024-06
Current date: 2026-10-01

Reasoning: low

# Valid channels: analysis, commentary, final. Channel must be included for every message.
Calls to these tools must go to the commentary channel: 'functions'.<|end|><|start|>user<|message|>Modify this existing python file.

File: plugin/core/handlers.py

Request:
Initialize final subclass of LanguageHandler

Current file:
from .types import ClientConfig
from .typing import List, Callable, Optional, Type
import abc


class LanguageHandler(metaclass=abc.ABCMeta):
    on_start = None  # type: Optional[Callable]
    on_initialized = None  # type: Optional[Callable]

    @abc.abstractproperty
    def name(self) -> str:
        raise NotImpleme

In [6]:
from trl import SFTConfig, SFTTrainer

FastLanguageModel.for_training(model)

trainer = SFTTrainer(
    model=model,
    processing_class=tokenizer,
    train_dataset=commit_data["train"],
    eval_dataset=commit_data["test"],
    args=SFTConfig(
        output_dir="/content/commitpack-v2-output",
        dataset_text_field="text",
        max_length=1024,
        per_device_train_batch_size=1,
        per_device_eval_batch_size=1,
        gradient_accumulation_steps=8,
        max_steps=10,
        learning_rate=1e-5,
        logging_steps=1,
        save_strategy="no",
        report_to="none",
    ),
)

trainer.train()
print(trainer.evaluate())

Unsloth: Switching to float32 training since model cannot work with float16

Unsloth: Tokenizing ["text"] (num_proc=2):   0%|          | 0/216 [00:00<?, ? examples/s]

Unsloth: Tokenizing ["text"] (num_proc=2):   0%|          | 0/24 [00:00<?, ? examples/s]

==((====))==  Unsloth - 2x faster free finetuning | Num GPUs used = 2
   \\   /|    Num examples = 216 | Num Epochs = 1 | Total steps = 10
O^O/ \_/ \    Batch size per device = 1 | Gradient accumulation steps = 8
\        /    Data Parallel GPUs = 1 | Total batch size (1 x 8 x 1) = 8
 "-____-"     Trainable parameters = 92,454,912 of 21,007,212,096 (0.44% trained)

Unsloth: Will smartly offload gradients to save VRAM!
Unsloth: Double buffering enabled (parallel H2D + compute) for backward pass.

Unsloth: Not an error, but GptOssForCausalLM does not accept `num_items_in_batch`.
Using gradient accumulation will be very slightly less accurate.
Read more on gradient accumulation issues here: https://unsloth.ai/blog/gradient

{'eval_loss': 3.4526443481445312, 'eval_runtime': 127.7549, 'eval_samples_per_second': 0.188, 'eval_steps_per_second': 0.188, 'epoch': 0.37037037037037035}

### Save

In [22]:
from google.colab import drive
from datetime import datetime

drive.mount("/content/drive")

save_path = (
    "/content/drive/MyDrive/AI learning/"
    "gpt-oss-commitpack-v3-" + datetime.now().strftime("%Y%m%d-%H%M%S")
)

# 当前模型同时装着 v1、v2，只保存继续训练的这一份
model.save_pretrained(
    save_path,
    selected_adapters=[v2_adapter],
)
tokenizer.save_pretrained(save_path)

print("已保存：", save_path)
print("如果 adapter 名称不是 default，文件在该路径下的同名子文件夹中。")

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).
已保存： /content/drive/MyDrive/AI learning/gpt-oss-commitpack-v3-20261001-081530
如果 adapter 名称不是 default，文件在该路径下的同名子文件夹中。

In [8]:
from unsloth import FastLanguageModel
from transformers import TextStreamer

FastLanguageModel.for_inference(model)

question = (
    "Fix this Python function. It must return the average, "
    "or None when the list is empty. Return only the corrected function.\n\n"
    "def average(numbers):\n"
    "    return sum(numbers) / len(numbers)\n"
)

inputs = tokenizer.apply_chat_template(
    [{"role": "user", "content": question}],
    add_generation_prompt=True,
    return_tensors="pt",
    reasoning_effort="low",
).to("cuda")

_ = model.generate(
    inputs,
    max_new_tokens=512,
    do_sample=False,
    streamer=TextStreamer(tokenizer, skip_prompt=True),
    pad_token_id=tokenizer.eos_token_id,
)

<|channel|>analysis<|message|>Need to handle empty list: if len==0 return None. Also handle division by zero. Provide corrected function.<|end|><|start|>assistant<|channel|>final<|message|>```python
def average(numbers):
    if not numbers:          # handles empty list
        return None
    return sum(numbers) / len(numbers)
```
<|return|>

In [17]:
from unsloth import FastLanguageModel

FastLanguageModel.for_inference(model)

# 记住当前 v2 adapter
v2_adapter = model.active_adapter

# 加载你保存的 v1；不需要再加载第二个完整模型
model.load_adapter(
    "/content/drive/MyDrive/AI learning/gpt-oss-fable-lora-v1",
    adapter_name="compare_v1",
    is_trainable=False,
)

question = (
    "Fix this Python function:\n\n"
    "def merge_settings(defaults, overrides):\n"
    "    defaults.update(overrides)\n"
    "    return defaults\n\n"
    "Requirements:\n"
    "- Recursively merge nested dictionaries.\n"
    "- Overrides take precedence.\n"
    "- Replace lists rather than concatenate them.\n"
    "- Do not modify either input.\n"
    "- Changes to nested dictionaries or lists in the result "
    "must not affect either input.\n"
    "- Use only the standard library.\n"
    "- Return only the corrected function."
)

def get_answer():
    inputs = tokenizer.apply_chat_template(
        [{"role": "user", "content": question}],
        add_generation_prompt=True,
        return_tensors="pt",
        reasoning_effort="low",
    ).to("cuda")

    output = model.generate(
        inputs,
        max_new_tokens=512,
        do_sample=False,
        pad_token_id=tokenizer.eos_token_id,
    )

    return tokenizer.decode(
        output[0][inputs.shape[-1]:],
        skip_special_tokens=True,
    )

try:
    model.set_adapter("compare_v1")
    v1_answer = get_answer()

    model.set_adapter(v2_adapter)
    v2_answer = get_answer()
finally:
    model.set_adapter(v2_adapter)

print("===== v1 =====")
print(v1_answer)
print("\n===== v2 =====")
print(v2_answer)

===== v1 =====
analysisWe need to provide corrected function. Ensure deep copy. Use copy.deepcopy. Use recursion. Return new dict.assistantfinal```python
def merge_settings(defaults, overrides):
    """
    Recursively merge two dictionaries.

    Parameters
    ----------
    defaults : dict
        The default settings.
    overrides : dict
        Settings that override the defaults.

    Returns
    -------
    dict
        A new dictionary containing the merged settings.
    """
    from copy import deepcopy

    def _merge(d1, d2):
        result = {}
        # keys from both dictionaries
        for key in set(d1) | set(d2):
            val1 = d1.get(key)
            val2 = d2.get(key)

            # If the key exists in both dictionaries
            if key in d1 and key in d2:
                # If both values are dictionaries, merge recursively
                if isinstance(val1, dict) and isinstance(val2, dict):
                    result[key] = _merge(val1, val2)
                # If both values are lists, replace the default list
                elif isinstance(val1, list) and isinstance(val2, list):
                    result[key] = deepcopy(val2)
                # Otherwise, the override value takes precedence
                else:
                    result[key] = deepcopy(val2)
            # If the key exists only in one dictionary
            elif key in d1:
                result[key] = deepcopy(val1)
            else:  # key in d2 only
                result[key] = deepcopy(val2)

        return result

    # Use deepcopy to avoid modifying the original inputs
    return _merge(deepcopy(defaults), deepcopy(overrides))
```

===== v2 =====
analysisWe need to provide corrected function. Ensure deep copy. Use copy.deepcopy. Use recursion. Return new dict.assistantfinal```python
def merge_settings(defaults, overrides):
    """
    Recursively merge two dictionaries.

    Parameters
    ----------
    defaults : dict
        The default settings.
    overrides : dict
        Settings that override the defaults.

    Returns
    -------
    dict
        A new dictionary containing the merged settings.
    """
    from copy import deepcopy

    def _merge(d1, d2):
        result = {}
        # keys from both dictionaries
        for key in set(d1) | set(d2):
            val1 = d1.get(key)
            val2 = d2.get(key)

            # If the key exists in both dictionaries
            if key in d1 and key in d2:
                # If both values are dictionaries, merge recursively
                if isinstance(val1, dict) and isinstance(val2, dict):
                    result[key] = _merge(val1, val2)
                # If both values are lists, replace the default list
                elif isinstance(val1, list) and isinstance(val2, list):
                    result[key] = deepcopy(val2)
                # Otherwise, override with the value from d2
                else:
                    result[key] = deepcopy(val2)
            # If the key exists only in d1
            elif key in d1:
                result[key] = deepcopy(val1)
            # If the key exists only in d2
            else:
                result[key] = deepcopy(val2)

        return result

    return _merge(deepcopy(defaults), deepcopy(overrides))
```

In [21]:
from unsloth import FastLanguageModel
from trl import SFTConfig, SFTTrainer

# 确认使用 v2，而不是比较时加载的 v1
model.set_adapter(v2_adapter)
FastLanguageModel.for_training(model)

trainer_next = SFTTrainer(
    model=model,
    processing_class=tokenizer,
    train_dataset=commit_data["train"],
    eval_dataset=commit_data["test"],
    args=SFTConfig(
        output_dir="/content/commitpack-v3-output",
        dataset_text_field="text",
        max_length=1024,
        per_device_train_batch_size=1,
        per_device_eval_batch_size=1,
        gradient_accumulation_steps=8,
        max_steps=10,
        learning_rate=5e-6,
        logging_steps=1,
        seed=123,
        save_strategy="no",
        report_to="none",
    ),
)

before = trainer_next.evaluate()["eval_loss"]
trainer_next.train()
after = trainer_next.evaluate()["eval_loss"]

print("训练前测试 loss：", before)
print("训练后测试 loss：", after)

Unsloth: Switching to float32 training since model cannot work with float16

Unsloth: Tokenizing ["text"] (num_proc=2):   0%|          | 0/216 [00:00<?, ? examples/s]

Unsloth: Tokenizing ["text"] (num_proc=2):   0%|          | 0/24 [00:00<?, ? examples/s]

==((====))==  Unsloth - 2x faster free finetuning | Num GPUs used = 2
   \\   /|    Num examples = 216 | Num Epochs = 1 | Total steps = 10
O^O/ \_/ \    Batch size per device = 1 | Gradient accumulation steps = 8
\        /    Data Parallel GPUs = 1 | Total batch size (1 x 8 x 1) = 8
 "-____-"     Trainable parameters = 92,454,912 of 21,099,667,008 (0.44% trained)

Unsloth: Will smartly offload gradients to save VRAM!
Unsloth: Double buffering enabled (parallel H2D + compute) for backward pass.

训练前测试 loss： 3.4526443481445312
训练后测试 loss： 3.0524709224700928

### Installation

In [1]:
%%capture
import os, importlib.util
!pip install --upgrade -qqq uv
if importlib.util.find_spec("torch") is None or "COLAB_" in "".join(os.environ.keys()):
    try: import numpy, PIL; _numpy = f"numpy=={numpy.__version__}"; _pil = f"pillow=={PIL.__version__}"
    except: _numpy = "numpy"; _pil = "pillow"
    !uv pip install -qqq \
        "torch>=2.8.0" "triton>=3.4.0" {_numpy} {_pil} torchvision bitsandbytes "transformers==4.56.2" \
        "unsloth_zoo[base] @ git+https://github.com/unslothai/unsloth-zoo" \
        "unsloth[base] @ git+https://github.com/unslothai/unsloth" \
        git+https://github.com/triton-lang/triton.git@0add68262ab0a2e33b84524346cb27cbb2787356#subdirectory=python/triton_kernels
elif importlib.util.find_spec("unsloth") is None:
    !uv pip install -qqq unsloth
!uv pip install --upgrade --no-deps transformers==4.56.2 "tokenizers>=0.22.0,<=0.23.0" trl==0.22.2 unsloth unsloth_zoo
!uv pip install --no-deps --upgrade "torchao>=0.16.0"

### Unsloth

We're about to demonstrate the power of the new OpenAI GPT-OSS 20B model through a finetuning example. To use our `MXFP4` inference example, use this [notebook](https://colab.research.google.com/github/unslothai/notebooks/blob/main/nb/GPT_OSS_MXFP4_(20B)-Inference.ipynb) instead.

In [ ]:
from unsloth import FastLanguageModel
import torch
max_seq_length = 1024
dtype = None

# 4bit pre quantized models we support for 4x faster downloading + no OOMs.
fourbit_models = [
    "unsloth/gpt-oss-20b-unsloth-bnb-4bit", # 20B model using bitsandbytes 4bit quantization
    "unsloth/gpt-oss-120b-unsloth-bnb-4bit",
    "unsloth/gpt-oss-20b", # 20B model using MXFP4 format
    "unsloth/gpt-oss-120b",
] # More models at https://huggingface.co/unsloth

model, tokenizer = FastLanguageModel.from_pretrained(
    model_name = "unsloth/gpt-oss-20b",
    dtype = dtype, # None for auto detection
    max_seq_length = max_seq_length, # Choose any for long context!
    load_in_4bit = True,  # 4 bit quantization to reduce memory
    full_finetuning = False, # [NEW!] We have full finetuning now!
    # token = "YOUR_HF_TOKEN", # HF Token for gated models
)

We now add LoRA adapters for parameter efficient finetuning - this allows us to only efficiently train 1% of all parameters.

In [ ]:
model = FastLanguageModel.get_peft_model(
    model,
    r = 8, # Choose any number > 0 ! Suggested 8, 16, 32, 64, 128
    target_modules = ["q_proj", "k_proj", "v_proj", "o_proj",
                      "gate_proj", "up_proj", "down_proj",],
    lora_alpha = 16,
    lora_dropout = 0, # Supports any, but = 0 is optimized
    bias = "none",    # Supports any, but = "none" is optimized
    # [NEW] "unsloth" uses 30% less VRAM, fits 2x larger batch sizes!
    use_gradient_checkpointing = "unsloth", # True or "unsloth" for very long context
    random_state = 3407,
    use_rslora = False,  # We support rank stabilized LoRA
    loftq_config = None, # And LoftQ
)

### Reasoning Effort
The `gpt-oss` models from OpenAI include a feature that allows users to adjust the model's "reasoning effort." This gives you control over the trade-off between the model's performance and its response speed (latency) which by the amount of token the model will use to think.

----

The `gpt-oss` models offer three distinct levels of reasoning effort you can choose from:

* **Low**: Optimized for tasks that need very fast responses and don't require complex, multi-step reasoning.
* **Medium**: A balance between performance and speed.
* **High**: Provides the strongest reasoning performance for tasks that require it, though this results in higher latency.

In [ ]:
from transformers import TextStreamer

messages = [
    {"role": "user", "content": "Solve x^5 + 3x^4 - 10 = 3."},
]
inputs = tokenizer.apply_chat_template(
    messages,
    add_generation_prompt = True,
    return_tensors = "pt",
    return_dict = True,
    reasoning_effort = "low", # **NEW!** Set reasoning effort to low, medium or high
).to("cuda")

_ = model.generate(**inputs, max_new_tokens = 64, streamer = TextStreamer(tokenizer))

Changing the `reasoning_effort` to `medium` will make the model think longer. We have to increase the `max_new_tokens` to occupy the amount of the generated tokens but it will give better and more correct answer

In [ ]:
from transformers import TextStreamer

messages = [
    {"role": "user", "content": "Solve x^5 + 3x^4 - 10 = 3."},
]
inputs = tokenizer.apply_chat_template(
    messages,
    add_generation_prompt = True,
    return_tensors = "pt",
    return_dict = True,
    reasoning_effort = "medium", # **NEW!** Set reasoning effort to low, medium or high
).to("cuda")

_ = model.generate(**inputs, max_new_tokens = 64, streamer = TextStreamer(tokenizer))

Lastly we will test it using `reasoning_effort` to `high`

In [ ]:
from transformers import TextStreamer

messages = [
    {"role": "user", "content": "Solve x^5 + 3x^4 - 10 = 3."},
]
inputs = tokenizer.apply_chat_template(
    messages,
    add_generation_prompt = True,
    return_tensors = "pt",
    return_dict = True,
    reasoning_effort = "high", # **NEW!** Set reasoning effort to low, medium or high
).to("cuda")

_ = model.generate(**inputs, max_new_tokens = 64, streamer = TextStreamer(tokenizer))

<a name="Data"></a>
### Data Prep

The `HuggingFaceH4/Multilingual-Thinking` dataset will be utilized as our example. This dataset, available on Hugging Face, contains reasoning chain-of-thought examples derived from user questions that have been translated from English into four other languages. It is also the same dataset referenced in OpenAI's [cookbook](https://cookbook.openai.com/articles/gpt-oss/fine-tune-transfomers) for fine-tuning. The purpose of using this dataset is to enable the model to learn and develop reasoning capabilities in these four distinct languages.

In [ ]:
def formatting_prompts_func(examples):
    convos = examples["messages"]
    texts = [tokenizer.apply_chat_template(convo, tokenize = False, add_generation_prompt = False) for convo in convos]
    return { "text" : texts, }

from datasets import load_dataset

dataset = load_dataset("HuggingFaceH4/Multilingual-Thinking", split = "train")
dataset

To format our dataset, we will apply our version of the GPT OSS prompt

In [ ]:
from unsloth.chat_templates import standardize_sharegpt
dataset = standardize_sharegpt(dataset)
dataset = dataset.map(formatting_prompts_func, batched = True,)

Let's take a look at the dataset, and check what the 1st example shows

In [ ]:
print(dataset[0]['text'])

What is unique about GPT-OSS is that it uses OpenAI [Harmony](https://github.com/openai/harmony) format which support conversation structures, reasoning output, and tool calling.

<a name="Train"></a>
### Train the model
Now let's train our model. We do 60 steps to speed things up, but you can set `num_train_epochs=1` for a full run, and turn off `max_steps=None`.

In [ ]:
from trl import SFTConfig, SFTTrainer
trainer = SFTTrainer(
    model = model,
    tokenizer = tokenizer,
    train_dataset = dataset,
    args = SFTConfig(
        per_device_train_batch_size = 1,
        gradient_accumulation_steps = 4,
        warmup_steps = 5,
        # num_train_epochs = 1, # Set this for 1 full training run.
        max_steps = 30,
        learning_rate = 2e-4,
        logging_steps = 1,
        optim = "adamw_8bit",
        weight_decay = 0.001,
        lr_scheduler_type = "linear",
        seed = 3407,
        output_dir = "outputs",
        report_to = "none", # Use TrackIO/WandB etc
    ),
)

We also use Unsloth's `train_on_completions` method to only train on the assistant outputs and ignore the loss on the user's inputs. This helps increase accuracy of finetunes and lower loss as well!

In [ ]:
from unsloth.chat_templates import train_on_responses_only

gpt_oss_kwargs = dict(instruction_part = "<|start|>user<|message|>", response_part = "<|start|>assistant<|channel|>final<|message|>")

trainer = train_on_responses_only(
    trainer,
    **gpt_oss_kwargs,
)

Let's verify masking the instruction part is done! Let's print the 100th row again.

In [ ]:
tokenizer.decode(trainer.train_dataset[100]["input_ids"])

Now let's print the masked out example - you should see only the answer is present:

In [ ]:
tokenizer.decode([tokenizer.pad_token_id if x == -100 else x for x in trainer.train_dataset[100]["labels"]]).replace(tokenizer.pad_token, " ")

In [ ]:
# @title Show current memory stats
gpu_stats = torch.cuda.get_device_properties(0)
start_gpu_memory = round(torch.cuda.max_memory_reserved() / 1024 / 1024 / 1024, 3)
max_memory = round(gpu_stats.total_memory / 1024 / 1024 / 1024, 3)
print(f"GPU = {gpu_stats.name}. Max memory = {max_memory} GB.")
print(f"{start_gpu_memory} GB of memory reserved.")

Let's train the model! To resume a training run, set `trainer.train(resume_from_checkpoint = True)`

In [ ]:
trainer_stats = trainer.train()

In [ ]:
# @title Show final memory and time stats
used_memory = round(torch.cuda.max_memory_reserved() / 1024 / 1024 / 1024, 3)
used_memory_for_lora = round(used_memory - start_gpu_memory, 3)
used_percentage = round(used_memory / max_memory * 100, 3)
lora_percentage = round(used_memory_for_lora / max_memory * 100, 3)
print(f"{trainer_stats.metrics['train_runtime']} seconds used for training.")
print(
    f"{round(trainer_stats.metrics['train_runtime']/60, 2)} minutes used for training."
)
print(f"Peak reserved memory = {used_memory} GB.")
print(f"Peak reserved memory for training = {used_memory_for_lora} GB.")
print(f"Peak reserved memory % of max memory = {used_percentage} %.")
print(f"Peak reserved memory for training % of max memory = {lora_percentage} %.")

<a name="Inference"></a>
### Inference
Let's run the model! You can change the instruction and input - leave the output blank!

In [ ]:
messages = [
    {"role": "system", "content": "reasoning language: French\n\nYou are a helpful assistant that can solve mathematical problems."},
    {"role": "user", "content": "Solve x^5 + 3x^4 - 10 = 3."},
]
inputs = tokenizer.apply_chat_template(
    messages,
    add_generation_prompt = True,
    return_tensors = "pt",
    return_dict = True,
    reasoning_effort = "medium",
).to("cuda")
from transformers import TextStreamer
_ = model.generate(**inputs, max_new_tokens = 64, streamer = TextStreamer(tokenizer))

<a name="Save"></a>
### Saving, loading finetuned models
To save the final model as LoRA adapters, either use Hugging Face's `push_to_hub` for an online save or `save_pretrained` for a local save.

**[NOTE]** Currently finetunes can only be loaded via Unsloth in the meantime - we're working on vLLM and GGUF exporting!

In [ ]:
model.save_pretrained("gpt_oss_lora")
# model.push_to_hub("hf_username/gpt_oss_lora", token = "YOUR_HF_TOKEN") # Save to HF

To run the finetuned model, you can do the below after setting `if False` to `if True` in a new instance.

In [ ]:
if False:
    from unsloth import FastLanguageModel
    model, tokenizer = FastLanguageModel.from_pretrained(
        model_name = "gpt_oss_lora", # YOUR MODEL YOU USED FOR TRAINING
        max_seq_length = 1024,
        dtype = None,
        load_in_4bit = True,
    )

messages = [
    {"role": "system", "content": "reasoning language: French\n\nYou are a helpful assistant that can solve mathematical problems."},
    {"role": "user", "content": "Solve x^5 + 3x^4 - 10 = 3."},
]
inputs = tokenizer.apply_chat_template(
    messages,
    add_generation_prompt = True,
    return_tensors = "pt",
    return_dict = True,
    reasoning_effort = "high",
).to("cuda")
from transformers import TextStreamer
_ = model.generate(**inputs, max_new_tokens = 64, streamer = TextStreamer(tokenizer))

### Saving to float16 for VLLM or mxfp4

We also support saving to `float16` or `mxfp4` directly. Select `merged_16bit` for float16. Use `push_to_hub_merged` to upload to your Hugging Face account! You can go to https://huggingface.co/settings/tokens for your personal tokens. See [our docs](https://unsloth.ai/docs/basics/inference-and-deployment) for more deployment options.

In [ ]:
# Merge and push to hub in mxfp4 4bit format
if False:
    model.save_pretrained_merged("gpt_oss_finetune_4bit", tokenizer, save_method = "mxfp4")
if False: model.push_to_hub_merged("repo_id/gpt_oss_finetune_4bit", tokenizer, token = "YOUR_HF_TOKEN", save_method = "mxfp4")

# Merge and push to hub in 16bit
if False:
    model.save_pretrained_merged("gpt_oss_finetune_16bit", tokenizer, save_method = "merged_16bit")
if False: # Pushing to HF Hub
    model.push_to_hub_merged("HF_USERNAME/gpt_oss_finetune_16bit", tokenizer, save_method = "merged_16bit", token = "YOUR_HF_TOKEN")

And we're done! If you have any questions on Unsloth, we have a [Discord](https://discord.gg/unsloth) channel! If you find any bugs or want to keep updated with the latest LLM stuff, or need help, join projects etc, feel free to join our Discord!

Some other resources:
1. Train your own reasoning model - Llama GRPO notebook [Free Colab](https://colab.research.google.com/github/unslothai/notebooks/blob/main/nb/Llama3.1_(8B)-GRPO.ipynb)
2. Saving finetunes to Ollama. [Free notebook](https://colab.research.google.com/github/unslothai/notebooks/blob/main/nb/Llama3_(8B)-Ollama.ipynb)
3. Llama 3.2 Vision finetuning - Radiography use case. [Free Colab](https://colab.research.google.com/github/unslothai/notebooks/blob/main/nb/Llama3.2_(11B)-Vision.ipynb)
4. See notebooks for DPO, ORPO, Continued pretraining, conversational finetuning and more on our [documentation](https://unsloth.ai/docs/get-started/unsloth-notebooks)!

<div class="align-center">
  <a href="https://unsloth.ai"><img src="https://github.com/unslothai/unsloth/raw/main/images/unsloth%20new%20logo.png" width="115"></a>
  <a href="https://discord.gg/unsloth"><img src="https://github.com/unslothai/unsloth/raw/main/images/Discord.png" width="145"></a>
  <a href="https://unsloth.ai/docs/"><img src="https://github.com/unslothai/unsloth/blob/main/images/documentation%20green%20button.png?raw=true" width="125"></a>

  Join Discord if you need help + ⭐️ <i>Star us on <a href="https://github.com/unslothai/unsloth">Github</a> </i> ⭐️
</div>

  This notebook and all Unsloth notebooks are licensed [LGPL-3.0](https://github.com/unslothai/notebooks?tab=LGPL-3.0-1-ov-file#readme).